site_name: Digital Talents
site_url: "https://gbssg.github.io/digital-talents"

nav:
  - 0. Übersicht: index.md
  - 1. Allgemeine Module:
    - Versionsverwaltung: 1-10.md
    - Linux Grundlagen / Shell: 1-20.md
    - Scripting Bash / PowerShell: 1-30.md
    - Container Technologien: 1-40.md
    - Cloud Technologien: 1-50.md
    - Modellieren von Datenstrukturen & Daten auswerten: 1-60.md
  - 2. Applikationsentwicklung:
    - Objektorientierte Programmierung (Blockwoche): 2-10.md
  - 3. ICT-Fachperson:
    - Support: 3-10.md
  - 4. Mediamatik:
    - Frontend-Entwicklung: 4-10.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  features:
    - navigation.instant
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 <a href='https://www.gbssg.ch'><span style='font-weight:1000'>gbs</span>sg.ch</a> <span class='green'>|</span> Digital Talents
extra:
  social:
    - icon: material/home
      link: https://www.gbssg.ch
      name: gbssg.ch
